# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
